### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ossphil** [uDeviceX/uDeviceX#9]
1. What version of uDeviceX is the issue happening on?
master branch updated to latest version

2. What platform and version?
Ubuntu 18.04, with mpich and hdf5
The CXXFLAGS was set as
```shell
export CXXFLAGS='-I/usr/include/mpich/ -I/usr/include/hdf5/mpich/'
```

When following the [Installation procedure](https://amlucas.github.io/udoc/src/install.html) compilation errors occur at the last command 'u.make -j4'. I pasted the outpus at https://pastebin.com/C5jD3isX. Any suggestions? Thanks.

**Comment by slitvinov** [comment]
Thank you for the detailed report. 

Please make sure `bop` is passing the tests: in `bop/` run
```
make test
```

If it is OK try the following in `udx/src`
```
cp make/sys/lisergey.acer sys.mk
u.make LOG=
```
This is the configuration I am using on ubuntu. In `sys.mk` `pkg-config` is used to set compiler and linker flags.

**Comment by ossphil** [comment]
slitvinov, thanks for your help. 
The test of `bop`:
```
...
atest: PASSED : ascii2ascii.t1
atest: 2/2 test(s) passed
make[1]: Leaving directory '/home/hui/workspace/bop/utils'
```
But errors persist while running `u.make -j4 LOG=`: https://pastebin.com/n3ZEvVtB.
Seems there are some problems linking to `bop`.

**Comment by slitvinov** [comment]
I think I can reproduce it.

Try (`bop-config --libs` should show where `libbop` is if you installed it differently) 
```
$ nm ~/prefix/bop/lib/libbop_mpi.a | grep bop_read_header | c++filt
```

If `bop` was built with `openmpi` it returns
```
0000000000000880 T bop_read_header(ompi_communicator_t*, char const*, BopData*, char*)
```

To rebuild `bop` with `mpich` I do in `bop/`
```
$ make clean install MPICXX=mpicxx.mpich
```

the signature changes to
```
0000000000000850 T bop_read_header(int, char const*, BopData*, char*)
```

This version should link with `udx`.

**Comment by ossphil** [comment]
slitvinov, thanks for your solution. It works! I noticed `udx` depends on `mpich` but forgot to recompile `bop` with `mpich`. Maybe the `mpich` dependency should been added to the `installation procedure` to avoid similar errors for others?

Another question: 
Is `udx` compatible with higher `cuda` versions than 8.0? The original `sys.mk` looks for `cuda-8.0`, but i compiled successfully with `cuda-10.0`.
